### ISSUE TITLE
Redraw of plots with shiny

### ISSUE THREAD

**Issue by SemiQuant** [zachcp/phylocanvas#3]
Hi,

I'm trying to use phylocanvas with shiny but each time I change a parameter and redraw the plot, it renders it as a new plot below the previous one (instead of replacing it). 

```R
require(shiny)
require(phylocanvas)
require(ape)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("nodes_in",
                  "Number of nodes",
                  min = 1, max = 50, value = 30)
    ),
    mainPanel(
      phylocanvasOutput("phy_test")
    )
  )
)

server <- function(input, output) {
  output$phy_test <- renderPhylocanvas({ #env = parent.frame(1), quoted = T
    tree <- rtree(n = input$nodes_in)
    phycanv <- phylocanvas(tree)
    phycanv
  })
}

shinyApp(ui = ui, server = server)

```

**Comment by zachcp** [comment]
hmm. curious. thanks for the example. I'll take a look

**Comment by zachcp** [comment]
hi @sciencebuff  can you try to reinstall from the repo. This works for me and should now be fixed.  I didn't have a method to delete the previous node. So each time you were updating, a new canvas was being appended to the webpage. 

Also, please let me know if you make something cool with this.

zach cp

**Comment by SemiQuant** [comment]
Thanks @zachcp, working great now. I'll let you know if I make anything worth mentioning.
